fix `-Wcast-function-type` build issues
aws/aws-lc pull request #1972
Opened 2024-11-06 23:36 UTC by vszakats

### Issues:
Resolves #1971

### Description of changes: 
- silence `-Werror,-Wcast-function-type-mismatch` in `crypto/rand_extra/windows.c`.
- extend `-Wno-cast-function-type` to clang versions supporting it.
  Should address https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/96 also for clang builds.
  Ref: #155

### Call-outs:

### Testing:
I build-tested both changes.

2024-11-07 03:10 UTC, andrewhop approved these changes

2024-11-07 22:59 UTC, torben-hansen requested changes
Please add license statement in PR description.

> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license.

2024-11-08 02:44 UTC, vszakats commented
Done

2024-11-08 02:59 UTC, samuel40791765 approved these changes

2024-11-08 14:56 UTC, torben-hansen approved these changes

2024-11-08 14:57 UTC, merged

2024-11-08 14:57 UTC, torben-hansen commented
Thanks! Merged it.